services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - AUTH_SERVICE_URL=http://auth-service:8081
      - ITEM_SERVICE_URL=http://item-service:8082

    depends_on:
      - auth-service
      - redis

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - JWT_SECRET=mysecretkey
      - DATABASE_URL=postgresql://user:password@db:5432/authdb?sslmode=disable

    depends_on:
      - db
      - redis

    restart: always

  item-service:
    build: ./item-service
    ports:
      - "8082:8082"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db:5432/authdb
    depends_on:
      - db

  frontend:
    build: ./frontend-service
    ports:
      - "8003:80"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8080

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
